# Generated by Django 4.2.1 on 2023-06-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eslapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlist",
            name="jan_cd",
            field=models.CharField(
                blank=True,
                default=4973007525936,
                max_length=100,
                null=True,
                verbose_name="JANコード",
            ),
        ),
        migrations.AlterField(
            model_name="productlist",
            name="product_cd",
            field=models.CharField(
                default=111111,
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="商品コード",
            ),
        ),
    ]
