# Generated by Django 4.2.1 on 2023-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eslapp", "0002_alter_productlist_jan_cd_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateList",
            fields=[
                ("inch", models.CharField(max_length=8)),
                (
                    "module_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("readable_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "TemplateList",
            },
        ),
    ]
